#!/bin/sh
### TYPE: upload-python

# Wait for network to settle
echo "Waiting for IP address..."

# With Static IP, this should be instant. We loop just in case interface is down.
while [ -z "$(hostname -I | grep 10.)" ]; do
    sleep 1
done
echo "Network up: $(hostname -I)"
sleep 0.5

export PYTHONUNBUFFERED=1

# Activate the virtual environment
# Note: The setup script ensures this path exists.
# Using "." is POSIX compliant (same as source)
. $HOME/robo2025/bin/activate

# Run the Multi-Process Supervisor
# This script will spawn the individual camera nodes
python3 main_single_processor.py --autorestart --vision config/vision.json --frc /boot/frc.json