// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2429.Spartan2018.unused;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc2429.Spartan2018.Robot;

/**
 *   This command controls the lifter with a joystick - manual power mode
 */
public class LifterWithStick extends Command {
	

    public LifterWithStick() {
        requires(Robot.liftMechanism);
   }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	System.out.println("\nEntering Lifter With Stick at " + String.format("%.2f",Timer.getFPGATimestamp()) + "s");
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	// Velocity Mode
    	//Robot.liftMechanism.setVelocity(Robot.oi.driveStick);
    	// Percent output mode
    	// Robot.liftMechanism.setOutput(Robot.oi.driveStick);
    	// Position control mode
    	Robot.liftMechanism.setPosition(Robot.oi.driveStick);
    }
    
    
	//------------------------------------------------------------------------------------

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	Robot.liftMechanism.stop();
    	System.out.println("Ending Lifter With Stick at " + String.format("%.2f",Timer.getFPGATimestamp()) + "s");
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	Robot.liftMechanism.stop();
    	System.out.println("Interrupting Lifter With Stick at " + String.format("%.2f",Timer.getFPGATimestamp()) + "s");
    }
}
