// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2429.Spartan2018.subIntake;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc2429.Spartan2018.Robot;

/**
 *   This command controls the Intake with a joystick - manual power mode
 */
public class IntakeWithStick extends Command {
	Joystick joy;

    public IntakeWithStick() {
        requires(Robot.intake);
   }

    public IntakeWithStick(Joystick joy) {
        requires(Robot.intake);
        this.joy = joy;
   }
    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	System.out.println("\nEntering Intake With Stick at " + String.format("%.2f",Timer.getFPGATimestamp()) + "s");
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	Robot.intake.intakeDrive(joy);
    }
    
    
	//------------------------------------------------------------------------------------

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	Robot.intake.intakeStop();
    	System.out.println("Ending Intake With Stick at " + String.format("%.2f",Timer.getFPGATimestamp()) + "s");
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	Robot.intake.intakeStop();
    	System.out.println("Interrupting Intake With Stick at " + String.format("%.2f",Timer.getFPGATimestamp()) + "s");
    }
}
