// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2429.Spartan2018.subLifter;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2429.Spartan2018.Robot;

/**
 *  Placeholder - intending to send this a position (down, middle, up, etc)
 */
public class LifterBottom extends Command {
    public LifterBottom() {
        requires(Robot.liftMechanism);
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	System.out.println("LifterBottom called at: "  + String.format("%.2f", Timer.getFPGATimestamp()- Robot.enabledTime)  + "s");
    	Robot.liftMechanism.setArmMoving(true);
    	//Robot.liftMechanism.lifterMoveToBottom();
    	setTimeout(3);
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	Robot.liftMechanism.moveDown();
    	Timer.delay(0.015);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return (Robot.liftMechanism.getArmSetpoint() < 200);
    	//return !Robot.liftMechanism.isArmMoving();
    	//return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	System.out.println("LifterBottom ended at: "  + String.format("%.2f", Timer.getFPGATimestamp()- Robot.enabledTime)  + "s");
    	Robot.liftMechanism.setArmMoving(false);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	System.out.println("LifterBottom interrupted at: "  + String.format("%.2f", Timer.getFPGATimestamp()- Robot.enabledTime)  + "s");
    	Robot.liftMechanism.setArmMoving(false);
    }
}
