package org.usfirst.frc2429.Spartan2018.commands;

// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2429.Spartan2018.Robot;

/**
 *
 */
public class ClimberReverseToggle extends Command {


    public ClimberReverseToggle() {
        requires(Robot.climber);
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	System.out.println("\nEntering Climber Reverse Toggle at " + String.format("%.2f",Timer.getFPGATimestamp()) + "s");
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	System.out.println("Executing Climber Reverse Toggle at " + String.format("%.2f",Timer.getFPGATimestamp()) + "s");
    	Robot.climber.climberReverseToggle();
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return true;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	//Nothing to clean up
    	System.out.println("Ending Climber Reverse Toggle at " + String.format("%.2f",Timer.getFPGATimestamp()) + "s");
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	//Nothing to clean up
    	System.out.println("Interrupting Climber Reverse Toggle at " + String.format("%.2f",Timer.getFPGATimestamp()) + "s");
    }
}
