// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team2429.spartan2017.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc.team2429.spartan2017.OI;
import org.usfirst.frc.team2429.spartan2017.Robot;

/**
 * This command is used to calibrate out the xbox joystick's issues
 * Call it at the beginning of autonomous and teleop
 * Seems like it wouldn't be needed at autonomous... really this should be an OI method
 * that is called in the Robot init instead of using the command
 */
public class CalibrateJoystick extends Command {

    public CalibrateJoystick() {

    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.oi.calibrateJoystick();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {

    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return true;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
